### ISSUE TITLE
Upload Video of seminar (session 2 video is missing as link for cloud)

### ISSUE THREAD

**Issue by friederikelbauer** [LS-Shikano/survey-experiments-seminar#3]
I cant find the link to the session 2 video (otree_session2_errorhandling_groupvariables on the fileserver). I want to link all the videos of the seminar to our documentation so it would be nice if you could upload it to the cloud and then send me the link to it.

**Comment by SuShikano** [comment]
Sorry for my late response, but where can I find the file???

**Comment by friederikelbauer** [comment]
It should be on the fileserver! In the video folder and then the otree_session2_errorhandling_groupvariables video

**Comment by SuShikano** [comment]
Ah, now I found it. There are two folders whose names are very similar to each other. I am now making the file names consistently and create new links. I will post here all the link.

**Comment by SuShikano** [comment]
Here the links. Please check them!

session1 getting started
https://cloud.uni-konstanz.de/index.php/s/gcmAn2NtHSj2gZa  
session1 adding page
https://cloud.uni-konstanz.de/index.php/s/nDX4G4jL5wSKs8g
session2 error handling
https://cloud.uni-konstanz.de/index.php/s/PDXHeJDqEJe5RcN
session5 bot testing 1
https://cloud.uni-konstanz.de/index.php/s/Ks6fCAqLGRD5zgJ
session5 bot testing 2
https://cloud.uni-konstanz.de/index.php/s/Z8yzMf2aSsK5cFB
session6 heroku overview
https://cloud.uni-konstanz.de/index.php/s/5HiW5Cr8MQnjLXS
session6 heroku deployment
https://cloud.uni-konstanz.de/index.php/s/FTiZWYLBS9TpbT8

**Comment by SuShikano** [comment]
I have put all videos in the fileserver under: \\files.uni-konstanz.de\LS_Shikano_Hiwis\Lehre\SS22OnlineSurveyExperiments

**Comment by friederikelbauer** [comment]
yes, all good. Thanks!
